logging:
  level:
    com.hxy.nzxy.stexam: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3376/stexam?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: liuzailin
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
     jpa:
        database : MYSQL
        show-sql : true
  redis:
    # Redis服务器地址
    hostName: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: root
    # 连接超时时间（毫秒）
    timeout: 0
    # 连接池
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      maxActive: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      maxWait: -1
      # 连接池中的最大空闲连接
      maxIdle: 8
      # 连接池中的最小空闲连接
      minIdle: 0
#分页配置
page:
  size: 20
#项目配置
stexam:
  exportTable:
    exportTableUrl: ''
  uploadPath:
    summernote: ''
    summernoteUrl: ''
    summernoteFileExtension: ''
ftp:
  address: 218.240.154.15
  port: 21
  username: nzxy
  password: Nzxy@1234
  basepath: /home/ftppic
  baseUrl: http://ftp.mukexiaoyuan.com:8899/